Update jq filter for efo_otar_slim.owl
opentargets/platform-input-support pull request #103
Opened 2023-07-28 13:17 UTC by ehsanb29

Update jq filter for efo_otar_slim.owl in EFO version v3.56.0.
Relevant issue: [3029](https://github.com/opentargets/issues/issues/3029)

2023-08-17 11:07 UTC, DSuveges commented
@jdhayhurst , based on discussion with Zoe, EFO introduced this update sometime in April. Therefore the May release was certainly impacted, however at that time the fix was not in place.

2023-08-31 11:04 UTC, ehsanb29 commented on modules/common/Riot.py
>          jq_cmd = f"{self.jq_cmd} -r '{owl_jq}' {riot_outfile} > {path_output}"
> I suspect _path_output_ was being serialized to _str_ here, so the command was working fine, but, when returned back to the caller on line _74_, it was being passed as a Path object, and that’s why it was not working.

Considering that the issue with `Path` is solved in the [PR 110](https://github.com/opentargets/platform-input-support/pull/110/commits/de4c8eef8c8a106b7bdb99c323e3535c4cd3055f), Can I ignore this change?

2023-08-31 11:21 UTC, mbdebian commented on modules/common/Riot.py
>          jq_cmd = f"{self.jq_cmd} -r '{owl_jq}' {riot_outfile} > {path_output}"
Before moving this PR forward, you’ll need to either pull the fix through a merge from _master_ when PR 110 is merged, or cherry pick the update from that PR

2023-09-05 09:06 UTC, mbdebian requested changes
Thanks for the PR @ehsanb29 , would you mind getting up to speed with the master branch?

2023-09-06 12:19 UTC, mbdebian approved these changes
Thanks @ehsanb29

2023-09-06 12:31 UTC, merged